name: Deploy Pipeline
on:
  push:
    branches:
      - main
      - workflow-update
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      image-tags: ${{ steps.build.outputs.image-tags }}
      image-digest: ${{ steps.build.outputs.image-digest }}
      sha-tag: ${{ steps.build.outputs.sha-tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build and Push Docker Image
        id: build
        uses: ./.github/actions/docker-build-push
        with:
          image-name: ${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  prod-deploy:
    runs-on: k8s-prod-k3s
    needs: [build-and-push-image]
    if: (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch') && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Complete Deployment
        uses: ./.github/actions/complete-deployment
        with:
          image-tag: ${{ needs.build-and-push-image.outputs.sha-tag }}
          secrets-json: |
            {
              "DB_HOST": "${{ secrets.DB_HOST }}",
              "DB_PORT": "${{ secrets.DB_PORT }}",
              "DB_USER": "${{ secrets.DB_USER }}",
              "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
              "DB_NAME": "${{ secrets.DB_NAME }}"
            }
